import { test, expect } from '@playwright/test';

test('saved recovery code resets a password once and revokes the signed-in session', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const email = `recovery-browser-${Date.now()}@example.test`;
  await page.goto('/');
  await page.locator('#nav-signup').click();
  await page.locator('#signup-name').fill('Recovery Tester');
  await page.locator('#signup-email').fill(email);
  await page.locator('#signup-password').fill('original-password-123');
  await page.locator('#signup-workspace').fill('Recovery Test');
  await page.locator('#signup-legal-consent').check();
  await page.locator('#signup-form button[type="submit"]').click();
  await page.locator('#cloud-save-recovery-btn').click();
  await page.locator('#recovery-password').fill('wrong-password');
  await page.getByRole('button', { name: 'Generate new recovery codes' }).click();
  await expect(page.locator('#recovery-status')).toContainText('incorrect');
  await page.locator('#recovery-password').fill('original-password-123');
  const issued = page.waitForResponse('**/api/auth/recovery-codes');
  await page.getByRole('button', { name: 'Generate new recovery codes' }).click();
  expect((await issued).headers()['cache-control']).toContain('no-store');
  const list = page.locator('#recovery-code-list');
  await expect(list).toBeVisible();
  const codes = (await list.inputValue()).split('\n');
  expect(codes).toHaveLength(8);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.locator('#recovery-back').click();
  await page.locator('#cloud-avatar-btn').click();
  await page.locator('#cloud-logout-btn').click();
  await page.locator('#nav-login').click();
  await page.locator('#goto-forgot').click();
  await page.getByRole('button', { name: 'Use a saved recovery code' }).click();
  await page.locator('#recovery-email').fill(email);
  await page.locator('#recovery-code').fill(codes[0]);
  await page.locator('#recovery-password').fill('replacement-password-123');
  await page.getByRole('button', { name: 'Reset password with code' }).click();
  await expect(page.locator('#recovery-status')).toContainText('Password changed');
  const reuse = await page.request.post('/api/auth/recovery-code/confirm', { data: { email, code: codes[0], password: 'attacker-password-123' } });
  expect(reuse.status()).toBe(400);
  const oldLogin = await page.request.post('/api/auth/login', { data: { email, password: 'original-password-123' } });
  expect(oldLogin.status()).toBe(401);
  const newLogin = await page.request.post('/api/auth/login', { data: { email, password: 'replacement-password-123' } });
  expect(newLogin.status()).toBe(200);
  const recoveredSession = await page.request.get('/api/auth/me');
  expect((await recoveredSession.json()).authenticated).toBe(true);
  const second = await page.request.post('/api/auth/recovery-code/confirm', { data: { email, code: codes[1], password: 'second-password-123' } });
  expect(second.status()).toBe(200);
  expect((await (await page.request.get('/api/auth/me')).json()).authenticated).toBe(false);
  expect(errors).toEqual([]);
});
