CREATE TABLE meta (
    [key] TEXT PRIMARY KEY,
    value TEXT NOT NULL
)
CREATE TABLE companies (
    id TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    normalized_name TEXT,
    display_name TEXT,
    display_name_normalized TEXT,
    industry TEXT,
    location TEXT,
    domain TEXT,
    careers_url TEXT,
    owner TEXT,
    owner_normalized TEXT,
    priority TEXT,
    priority_tier TEXT,
    status TEXT,
    outreach_status TEXT,
    connection_count INTEGER,
    senior_contact_count INTEGER,
    talent_contact_count INTEGER,
    buyer_title_count INTEGER,
    target_score REAL,
    daily_score REAL,
    follow_up_score REAL,
    job_count INTEGER,
    open_role_count INTEGER,
    new_role_count_7d INTEGER,
    stale_role_count_30d INTEGER,
    department_focus TEXT,
    department_focus_count INTEGER,
    department_concentration REAL,
    hiring_spike_score REAL,
    network_strength TEXT,
    hiring_status TEXT,
    last_job_posted_at TEXT,
    last_contacted_at TEXT,
    days_since_contact INTEGER,
    stale_flag TEXT,
    next_action TEXT,
    next_action_at TEXT,
    recommended_action TEXT,
    outreach_draft TEXT,
    top_contact_name TEXT,
    top_contact_title TEXT,
    ats_types_text TEXT,
    tags_text TEXT,
    notes TEXT,
    search_text TEXT,
    data_json TEXT NOT NULL
, [canonical_domain] TEXT, [linkedin_company_slug] TEXT, [aliases_text] TEXT, [enrichment_status] TEXT, [enrichment_source] TEXT, [enrichment_confidence] TEXT, [enrichment_confidence_score] REAL, [enrichment_notes] TEXT, [enrichment_evidence] TEXT, [enrichment_failure_reason] TEXT, [enrichment_attempted_urls_text] TEXT, [last_enriched_at] TEXT, [last_verified_at] TEXT, [next_enrichment_attempt_at] TEXT)
CREATE TABLE contacts (
    id TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    account_id TEXT,
    normalized_company_name TEXT,
    company_name TEXT,
    full_name TEXT,
    title TEXT,
    email TEXT,
    linkedin_url TEXT,
    connected_on TEXT,
    priority_score REAL,
    company_overlap_count INTEGER,
    outreach_status TEXT,
    notes TEXT,
    search_text TEXT,
    data_json TEXT NOT NULL
)
CREATE TABLE jobs (
    id TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    account_id TEXT,
    normalized_company_name TEXT,
    company_name TEXT,
    title TEXT,
    normalized_title TEXT,
    department TEXT,
    location TEXT,
    employment_type TEXT,
    job_id TEXT,
    url TEXT,
    job_url TEXT,
    source_url TEXT,
    ats_type TEXT,
    posted_at TEXT,
    retrieved_at TEXT,
    imported_at TEXT,
    last_seen_at TEXT,
    dedupe_key TEXT,
    active INTEGER,
    is_new INTEGER,
    is_gta INTEGER,
    search_text TEXT,
    data_json TEXT NOT NULL
)
CREATE TABLE board_configs (
    id TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    account_id TEXT,
    normalized_company_name TEXT,
    company_name TEXT,
    ats_type TEXT,
    board_id TEXT,
    domain TEXT,
    careers_url TEXT,
    source TEXT,
    notes TEXT,
    active INTEGER,
    last_checked_at TEXT,
    discovery_status TEXT,
    discovery_method TEXT,
    last_import_at TEXT,
    last_import_status TEXT,
    search_text TEXT,
    data_json TEXT NOT NULL
, [resolved_board_url] TEXT, [supported_import] INTEGER, [last_resolution_attempt_at] TEXT, [next_resolution_attempt_at] TEXT, [confidence_score] REAL, [confidence_band] TEXT, [evidence_summary] TEXT, [review_status] TEXT, [failure_reason] TEXT, [redirect_target] TEXT, [matched_signatures_text] TEXT)
CREATE TABLE activities (
    id TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    account_id TEXT,
    normalized_company_name TEXT,
    summary TEXT,
    type TEXT,
    notes TEXT,
    occurred_at TEXT,
    pipeline_stage TEXT,
    data_json TEXT NOT NULL
)
CREATE TABLE import_runs (
    id TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    run_type TEXT,
    status TEXT,
    started_at TEXT,
    completed_at TEXT,
    data_json TEXT NOT NULL
)
CREATE TABLE snapshots (
    name TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    source_revision TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    build_ms INTEGER NOT NULL
)
CREATE TABLE background_jobs (
    id TEXT PRIMARY KEY,
    job_type TEXT NOT NULL,
    status TEXT NOT NULL,
    summary_text TEXT,
    queued_at TEXT NOT NULL,
    started_at TEXT,
    finished_at TEXT,
    updated_at TEXT NOT NULL,
    progress_message TEXT,
    error_message TEXT,
    records_affected INTEGER,
    cancel_requested INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    result_json TEXT
)
CREATE TABLE resolver_coverage_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    captured_at TEXT NOT NULL,
    data_revision TEXT,
    total_configs INTEGER NOT NULL,
    resolved_configs INTEGER NOT NULL,
    unresolved_configs INTEGER NOT NULL,
    high_confidence_count INTEGER NOT NULL,
    medium_confidence_count INTEGER NOT NULL,
    low_confidence_count INTEGER NOT NULL,
    auto_active_count INTEGER NOT NULL,
    coverage_pct REAL NOT NULL
)
CREATE TABLE sqlite_sequence(name,seq)
CREATE TABLE enrichment_coverage_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    captured_at TEXT NOT NULL,
    data_revision TEXT,
    total_companies INTEGER NOT NULL,
    canonical_domain_count INTEGER NOT NULL,
    careers_url_count INTEGER NOT NULL,
    aliases_count INTEGER NOT NULL,
    enriched_count INTEGER NOT NULL,
    unenriched_count INTEGER NOT NULL,
    resolution_with_enrichment_count INTEGER NOT NULL,
    resolution_without_enrichment_count INTEGER NOT NULL,
    coverage_pct REAL NOT NULL
)

